### ISSUE TITLE
Elden Ring 1.03.2 Support

### ISSUE THREAD

**Issue by fabiogras** [bladecoding/DarkSouls3RemoveIntroScreens#11]
Hello, thank you for this.
After updating Elden Ring to 1.03.2 controller is non-functional.
Popup displays "Unable to apply patch to elden ring. You may be running an unsupported version.". I guess you apply the patch per version?

**Comment by Kohtas** [comment]
Dropping a confirmation here, it seems this mod is currently causing a prompt to let you know it can't apply the patch (even though the patch is actually applied). Myself and many others from the Nexus site have had this issue and removing this mod has fixed it. We'll just have to hang tight and wait for an updated version.

**Comment by BlazeOfHell** [comment]
New reladdr seems to be ab020d. adding below patch allowed logo skip to work

		Patch{ 0xAB020D, 2, { static_cast<char>(0x90), static_cast<char>(0x90) },
						{ static_cast<char>(0x74), static_cast<char>(0x53) } }

**Comment by bladecoding** [comment]
https://github.com/bladecoding/DarkSouls3RemoveIntroScreens/releases/tag/v8

**Comment by fabiogras** [comment]
> https://github.com/bladecoding/DarkSouls3RemoveIntroScreens/releases/tag/v8

Works fine on my end.
Thank you for this.
