### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Aemony** [bladecoding/DarkSouls3RemoveIntroScreens#13]
Hi, first I'd like to thank you for the Elden Ring intro skip mod, as it served me well while I used it. I appreciate the work that went into creating the initial skip.

However let me ask you a question: where is the benefit of a supposed "no intro" mod that **prolongs** the launch period of a game every time it detects an unsupported version?

I get that you want it to inform the user about being used with an unsupported version, but throwing up a message box on each launch isn't exactly a "neutral" approach with no net benefits/downsides -- in fact it's arguably a fully negative approach since it means the launch times of the game will be prolonged until such a time that the user either clicks pass the message box, updates the mod (which may take days), or outright removes it.

I would suggest either creating a log file or such, or simply not notify the user at all. The user will note the intros, after all, which itself is an indicator that something is wrong with the mod.

I ended up moving over to using an alternate no intros mod instead as that one not only survives game updates but also doesn't needlessly prompt me whenever it runs into an unsupported version: https://github.com/techiew/EldenRingMods/blob/master/SkipTheIntro/DllMain.cpp

**Comment by bladecoding** [comment]
> I would suggest either creating a log file 

It's hard enough to get people to read a readme let alone a log file.

> simply not notify the user at all

That didn't work which is why it was added in the first place
