### ISSUE TITLE
Crash on start for Dark Souls 3

### ISSUE THREAD

**Issue by tylermast** [bladecoding/DarkSouls3RemoveIntroScreens#5]
When including DINPUT8.DLL in the DS3 game directory, the program crashes on load. The game can start up until the point where I get a white screen then a black screen. Once it reaches the black screen the program crashes. I haven't heard of anyone having this kind of issue but I'm not sure what steps to take to troubleshoot.

**Comment by bladecoding** [comment]
Which version of ds3 and windows?

**Comment by tylermast** [comment]
Windows: 10 Pro Version 1607 OS Build 14393.1715
Dark Souls 3: Current Patch (1.15R1.35) after clean install
I have also attempted to use it on 1.12R1.31 as well to no avail.

**Comment by bladecoding** [comment]
Did you get DS3NoLogoMod_v1.15.zip or DS3NoLogoMod_v1.15b.zip? The first release did have a crash issue.

**Comment by tylermast** [comment]
1.15b crashes as well

**Comment by bladecoding** [comment]
If you are able to enable WER that would help. I'm guessing this might be a system configuration issue.

**Comment by tylermast** [comment]
Is this what you're looking for?

Log Name:      Application
Source:        Application Error
Date:          10/6/2017 9:56:56 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      ----
Description:
Faulting application name: DarkSoulsIII.exe, version: 1.15.0.0, time stamp: 0x598a43ef
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ffc14bc0398
Faulting process id: 0x2a60
Faulting application start time: 0x01d33f0f81347f2e
Faulting application path: D:\Program Files (x86)\Steam\steamapps\common\DARK SOULS III\Game\DarkSoulsIII.exe
Faulting module path: unknown
Report Id: 1f2e5418-a9c9-44fb-b608-c3c77465157c
Faulting package full name: 
Faulting package-relative application ID:

**Comment by bladecoding** [comment]
There should likely be a crash dump in C:\ProgramData\Microsoft\Windows\WER\ReportArchive.

**Comment by tylermast** [comment]
After reviewing the error report myself I noticed that Razer software was attempting to hook into the game as well. Disabling Razer Synapse's In-Game statistics function has fixed the problem.

[Report.wer.txt](https://github.com/bladecoding/DarkSouls3RemoveIntroScreens/files/1364244/Report.wer.txt)
