### ISSUE TITLE
Could you try this for Elden Ring?

### ISSUE THREAD

**Issue by Quzga** [bladecoding/DarkSouls3RemoveIntroScreens#9]
Was searching the web for removal of the annoying splash-screens and no luck, since you managed on Sekiro I was wondering if you have tried it on elden ring.

**Comment by bladecoding** [comment]
The intro code looks the same so the same patch should work. The only issue I see is that if you accidentally go online with it installed, you are a likely to get banned.  That's assuming EAC doesn't interfere with the injection/patch.

**Comment by Quzga** [comment]
Thanks for the reply! I tried it but it says eldenring.exe isn't supported or something.

**Comment by bladecoding** [comment]
It still needed to be updated. I was just stating that elden ring support would be trivial to add. Support for elden ring has been added. You can download it here. https://github.com/bladecoding/DarkSouls3RemoveIntroScreens/releases/tag/v4

**Comment by Quzga** [comment]
Thank you! Really appreciate it
